exclude: |
  (?x)^(
    iqe/data/plugin_skel/.*|
    iqe/tests/expected_results_test_ibutsu.py|
    iqe_base_services_api/.*|
    iqe_base_services_api51/.*|
    iqe_base_services_api6/.*
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        args:
          - '--fix'
      - id: ruff-format
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.1b3
    hooks:
      - id: hadolint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.16.0'
    hooks:
      - id: mypy
        additional_dependencies:
          - types-Pillow
          - types-jsonschema
          - types-tabulate
          - types-PyYAML
          - types-six
          - types-atomicwrites
          - types-tqdm
          - types-python-dateutil
          - types-requests
          - types-retry
          - backports.strenum
          - click
          - python-gitlab
          - pytest
          - pydantic>=2
  # If you have not run this hook on your system before, it may prompt you to
  # log in for patterns, and you will need to try again.
  # To enabe rh-pre-commit hook, users need to execute `pre-commit install`
  # Docs:
  # https://source.redhat.com/departments/it/it-information-security/leaktk/leaktk_components/rh_pre_commit
  - repo: https://gitlab.cee.redhat.com/infosec-public/developer-workbench/tools.git
    rev: rh-pre-commit-2.3.2
    hooks:
      - id: rh-pre-commit
      - id: rh-pre-commit.commit-msg # Optional for commit-msg attestation
  - repo: https://gitlab.cee.redhat.com/insights-qe/iqe-pre-commit-hooks
    rev: v25.01.22.0
    hooks:
    - id: iqe-checks
