---
apiVersion: v1
kind: Service
metadata:
  name: caddy
  labels:
    app.kubernetes.io/name: caddy
    app.kubernetes.io/instance: caddy
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: moto
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
    - port: 9000
      targetPort: http
      protocol: TCP
      name: metrics
    - port: 5432
      targetPort: http
      protocol: TCP
      name: database
  selector:
    app.kubernetes.io/name: caddy
    app.kubernetes.io/instance: caddy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: caddy
      app.kubernetes.io/instance: caddy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: caddy
        app.kubernetes.io/instance: caddy
    spec:
      serviceAccountName: caddy
      securityContext:
        {}
      volumes:
        - name: caddyfile
          configMap:
            name: caddyfile
      containers:
        - name: caddy
          securityContext:
            {}
          image: "quay.io/cloudservices/caddy-ubi:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: moto
              containerPort: 5000
              protocol: TCP
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: metrics
              containerPort: 9000
              protocol: TCP
            - name: database
              containerPort: 5432
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - name: caddyfile
              mountPath: /etc/caddy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: caddy
