= Generating Prometheus Metric Data

Metric data can be generated and imported to a local prometheus service run via podman. This is helpful when you'd like to test some metric gathering changes that aren't already in Observatorium.

== Generate The Test Data
The following script will create metrics in 5m intervals for the last 24 hours, and then runs prometheus with the mocked data. You can use env vars to influence the generated data (see ``bin/prometheus-mock-data.sh``).

[source,bash]
----
bin/prometheus-mock-data.sh
----

== Testing The API
http://localhost:9090/graph is useful to try PromQL queries.

Using ``START_DATE=$(date -d yesterday +%s)`` and ``END_DATE=$(date +%s)`` (last 24 hours) and plug them into the curl commands below.

[source,bash]
----
curl 'http://localhost:9090/api/v1/query_range?query=kafka_id%3Akafka_broker_quota_totalstorageusedbytes%3Amax_over_time1h_gibibytes+*+on%28_id%29+group_right+min_over_time%28ocm_subscription%7Bproduct%3D%22rhosak%22%2C+ebs_account%3D%22account123%22%2C+billing_model%3D%22marketplace%22%2C+support%3D%7E%22Premium%7CStandard%7CSelf-Support%7CNone%22%7D%5B1h%5D%29&dedup=true&partial_response=false&start=${START_DATE}&end=${END_DATE}&step=3600&max_source_resolution=0s'

# Example
curl 'http://localhost:9090/api/v1/query_range?query=kafka_id%3Akafka_broker_quota_totalstorageusedbytes%3Amax_over_time1h_gibibytes+*+on%28_id%29+group_right+min_over_time%28ocm_subscription%7Bproduct%3D%22rhosak%22%2C+ebs_account%3D%22account123%22%2C+billing_model%3D%22marketplace%22%2C+support%3D%7E%22Premium%7CStandard%7CSelf-Support%7CNone%22%7D%5B1h%5D%29&dedup=true&partial_response=false&start=1651449600&end=1651506600&step=3600&max_source_resolution=0s'
----

== Pointing Subscription Watch At The Local Prometheus
With this set up, you can now point the metering and tally services at this instance by running the application as follows.
[source,bash]
----
# Run the metering job
PROM_URL="http://localhost:9090/api/v1/" SPRING_PROFILES_ACTIVE=metering-job,kafka-queue ./gradlew :bootRun

# Run the swatch services.
SUBSCRIPTION_USE_STUB=true USER_USE_STUB=true DEV_MODE=true PROM_URL="http://localhost:9090/api/v1/" ./gradlew :bootRun
----
