---
version: '3.8'
services:
  artemis:
    image: quay.io/redhat-services-prod/rh-subs-watch-tenant/artemis
    container_name: artemis
    ports:
      - "61616:61616"  # core messaging (TCP)
      - "5672:5672"    # AMQP
    restart: unless-stopped