---
version: '3.1'
services:
  db:
    image: docker.io/postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init_dbs.sh:/docker-entrypoint-initdb.d/init_dbs.sh:z
    ports:
      - "5432:5432"
  kafka:
    image: docker.io/lensesio/fast-data-dev
    environment:
      - ADV_HOST=localhost
      - SAMPLEDATA=0
      - RUNNING_SAMPLEDATA=0
      - RUNTESTS=0
    ports:
      - "3030:3030"
      - "9092:9092"
      - "29092:29092"
  inventory:
    build:
      context: insights-host-inventory
      dockerfile: dev.dockerfile
