---
version: '3.1'
services:
  db:
    # Use the same version as in https://gitlab.cee.redhat.com/service/app-interface/-/blob/ff61d457898da76ebd4abf21fe3ce7b5c74c87a5/data/services/insights/rhsm/namespaces/rhsm-prod.yml#L179
    # When updating the image, remember to also update the following locations:
    # - SwatchPostgreSQLContainer.POSTGRESQL_IMAGE
    # - .github/workflows/validate-floorplan-queries.yaml (step "Setup Postgresql Database")
    image: quay.io/centos7/postgresql-12-centos7:centos7
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRESQL_MAX_CONNECTIONS=5000
      - POSTGRESQL_ADMIN_PASSWORD=admin
    volumes:
      - ./init_dbs.sh:/usr/share/container-scripts/postgresql/start/set_passwords.sh:z
      - ./postgresql.conf:/opt/app-root/src/postgresql-cfg/postgresql.conf:z
      - ./pg_hba.conf:/pg_hba.conf:z
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      swatch-network:
        aliases:
          - db
  kafka:
    container_name: swatch-kafka
    image: quay.io/strimzi/kafka:latest-kafka-3.1.0
    command: sh /init_kafka.sh
    environment:
      # Enable SSL debugging
      # - KAFKA_OPTS=-Djavax.net.debug=ssl,handshake,data,trustmanager,keymanager
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_SSL:SASL_SSL
      - KAFKA_LISTENERS=PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,CONTROLLER://:9093,SASL_SSL://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092,SASL_SSL://localhost:9094
      - LOG_DIR=/tmp/logs
      - KAFKA_SSL_CLIENT_AUTH=required
      - KAFKA_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/certs/server.jks
      - KAFKA_SSL_KEYSTORE_PASSWORD=password
      - KAFKA_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/certs/test-ca.jks
      - KAFKA_SSL_TRUSTSTORE_PASSWORD=password
        # Passed directly to the JVM. Place SSL debug options here (e.g. -Djavax.net.debug=ssl)
      - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
        # Note that as of this writing (20 Jul 2022), Kraft mode does not support SCRAM
      - KAFKA_SASL_MECHANISM=PLAIN
    ports:
      - "127.0.0.1:9092:9092"
      # Port 9093 is used by the Kraft configuration
      - "127.0.0.1:9094:9094"
      - "127.0.0.1:29092:29092"
    volumes:
      - ./config/kafka/init_kafka.sh:/init_kafka.sh:z
      - ./config/kafka/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf:z
      - ./config/kafka/:/etc/kafka/secrets/certs:z
    networks:
      swatch-network:
        aliases:
          - kafka
    user: 0
  kafka-rest:
    image: docker.io/confluentinc/cp-kafka-rest
    environment:
      - KAFKA_REST_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - kafka
  kafka-topics-ui:
    image: docker.io/landoop/kafka-topics-ui
    environment:
      - KAFKA_REST_PROXY_URL=http://kafka-rest:8082
      - PROXY=true
    ports:
      - "127.0.0.1:3030:8000"
    depends_on:
      - kafka-rest
  inventory:
    image: quay.io/cloudservices/insights-inventory
    entrypoint: /bin/bash -c
    command: ["FLASK_APP=./manage.py flask db upgrade; gunicorn -c gunicorn.conf.py -b 0.0.0.0:8000 -t 60 run"]
    environment:
      - INVENTORY_LOG_LEVEL=DEBUG
      - INVENTORY_DB_HOST=db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - prometheus_multiproc_dir=/tmp
      - BYPASS_RBAC=true
      - FLASK_APP=./manage.py
      - UNLEASH_TOKEN=*:*.placeholder
      - UNLEASH_CACHE_DIR=/tmp/.unleashcache
    depends_on:
      - kafka
      - db
    ports:
      - "127.0.0.1:8050:8000"
    user: 0
  inventory-mq:
    image: quay.io/cloudservices/insights-inventory
    entrypoint: /bin/bash -c
    command: ["./inv_mq_service.py"]
    environment:
      - INVENTORY_LOG_LEVEL=DEBUG
      - INVENTORY_DB_HOST=db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - prometheus_multiproc_dir=/tmp
      - BYPASS_RBAC=true
      - FLASK_APP=./manage.py
      - UNLEASH_TOKEN=*:*.placeholder
      - UNLEASH_CACHE_DIR=/tmp/.unleashcache
    depends_on:
      - kafka
      - db
    user: 0
  unleash:
    image: quay.io/cloudservices/unleash-server:4.21.0
    environment:
      - INIT_ADMIN_API_TOKENS=*:*.placeholder
      - CHECK_VERSION=false
      - DATABASE_HOST=db
      - DATABASE_NAME=unleash
      - DATABASE_USERNAME=${DATABASE_USER-insights}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD-insights}
      - DATABASE_SSL=false
      - IMPORT_DROP_BEFORE_IMPORT=false
      - IMPORT_FILE=/.unleash/flags.json
      - IMPORT_DROP_BEFORE_IMPORT=true
      - LOG_LEVEL=INFO
    ports:
      - 4242:4242
    volumes:
      - './.unleash:/.unleash:z'
networks:
  swatch-network:
    name: swatch-network
    driver: bridge
