docs_dir: ./docs
site_name: Subscription Watch Documentation
plugins:
- techdocs-core

nav:
- Home: index.md
- Api: api-documentation.md
- Iqe EE Proxy: iqe-ee-proxy.md
- Documentation:
    - Important Doc: /docs/default/Component/swatch-internal-docs

