docs_dir: ./docs
site_name: Subscription Watch Documentation
plugins:
- techdocs-core

nav:
- Home: index.md
- Api: api-documentation.md
- Iqe EE Proxy: iqe-ee-proxy.md
- Test Swatch: swatch-internal-documents.md
- Swatch Internal Docs: /docs/default/Component/swatch-internal-docs

