---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: wiremock
parameters: []
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: wiremock
      labels:
        app: wiremock
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: wiremock
      template:
        metadata:
          labels:
            app: wiremock
        spec:
          containers:
            - name: wiremock
              image: wiremock/wiremock:2.32.0
              env: []

  - apiVersion: v1
    kind: Service
    metadata:
      name: wiremock
    spec:
      selector:
        app: wiremock
      ports:
        - protocol: TCP
          port: 8101
          targetPort: 8080
