# This is a file maintained by the rhsm-subscription project that describes
# a portion of the Cloudigrade API.
openapi: "3.0.2"
info:
  title: "cloudigrade-api"
  description: "Third-party specification for Cloudigrade API"
  version: 1.0.0

paths:
  /users/:
    description: "Operations on users"
    parameters:
      - name: x-rh-cloudigrade-psk
        required: true
        in: header
        description: "Cloudigrade pre-shared key for authentication"
        schema:
          type: string
      - name: x-rh-cloudigrade-org-id
        required: false
        in: header
        description: "Cloudigrade org id"
        schema:
          type: string
      - name: x-rh-cloudigrade-account-number
        required: false
        in: header
        description: "Cloudigrade account number"
        schema:
          type: string
    get:
      summary: "Fetch user information"
      operationId: "ListCloudigradeUser"
      tags:
        - users
      responses:
        '200':
          description: "The operation completed successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
components:
  schemas:
    UserResponse:
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/CloudigradeUser"
        links:
          $ref: "#/components/schemas/CloudigradeUserLinksSection"
        meta:
          $ref: "#/components/schemas/CloudigradeUserMetaSection"
    CloudigradeUser:
      properties:
        date_joined:
          type: string
          format: date
        id:
          type: integer
        username:
          type: string
      required:
        - date_joined
        - id
        - username
    CloudigradeUserMetaSection:
      properties:
        count:
          type: integer
    CloudigradeUserLinksSection:
      properties:
        first:
          type: string
        last:
          type: string
        previous:
          type: string
        next:
          type: string
      required:
        - first
        - previous
        - last
        - next
