# See https://goessner.net/articles/JsonPath/ for JSON Path syntax

RHSM_RBAC_URL: ${clowder.dependency-endpoints.rbac.service.uri:http://localhost:8819}
RHSM_CONTRACTS_URL: ${clowder.endpoints.swatch-contracts-service.url:http://localhost:8011}
KESSEL_ENDPOINT: ${clowder.endpoints.kessel-inventory-api.hostname:localhost}:${KESSEL_INVENTORY_API_PORT:9000}

rhsm-subscriptions:
  pretty-print-json: ${PRETTY_PRINT_JSON:false}
  rbac-service:
    application-name: ${RHSM_RBAC_APPLICATION_NAME:subscriptions}
    url: ${RHSM_RBAC_URL}/api/rbac/v1
    authenticated: ${RBAC_AUTHENTICATED:${clowder.dependency-endpoints.rbac.service.authenticated:false}}
    truststore: ${RBAC_TRUST_STORE:${clowder.dependency-endpoints.rbac.service.trust-store-path:}}
    truststore-password: ${RBAC_TRUST_STORE_PASSWORD:${clowder.dependency-endpoints.rbac.service.trust-store-password:}}
    truststore-type: ${RBAC_TRUST_STORE_TYPE:${clowder.dependency-endpoints.rbac.service.trust-store-type:PKCS12}}
    max-connections: ${RHSM_RBAC_MAX_CONNECTIONS:100}
  kessel:
    endpoint: ${KESSEL_ENDPOINT}
    insecure: ${KESSEL_INSECURE:true}
    auth-enabled: ${KESSEL_AUTH_ENABLED:false}
    timeout-ms: ${KESSEL_TIMEOUT_MS:5000}
    rbac-base-endpoint: ${RBAC_BASE_ENDPOINT:${RHSM_RBAC_URL}}
    auth-oidc-issuer: ${KESSEL_AUTH_OIDC_ISSUER:}
    auth-client-id: ${KESSEL_AUTH_CLIENT_ID:}
    auth-client-secret: ${KESSEL_AUTH_CLIENT_SECRET:}
  contracts:
    client:
      back-off-initial-interval: ${CONTRACT_CLIENT_BACK_OFF_INITIAL_INTERVAL_MILLIS:1000}
      back-off-max-interval: ${CONTRACT_CLIENT_BACK_OFF_MAX_INTERVAL_MILLIS:64000}
      back-off-multiplier: ${CONTRACT_CLIENT_BACK_OFF_MULTIPLIER:2}
      max-attempts: ${CONTRACT_CLIENT_MAX_ATTEMPTS:1}
      url: ${RHSM_CONTRACTS_URL}
      truststore: ${clowder.endpoints.swatch-contracts-service.trust-store-path:}
      truststore-password: ${clowder.endpoints.swatch-contracts-service.trust-store-password}
      truststore-type: ${clowder.endpoints.swatch-contracts-service.trust-store-type}
      psk: ${SWATCH_SELF_PSK:placeholder}
