name: RHELProducts
products:
  - engProductId: 68 # Red Hat Enterprise Linux Desktop
    swatchProductIds:
      - RHEL
      - RHEL for x86
      - RHEL Desktop
  - engProductId: 69 # Red Hat Enterprise Linux Server
    swatchProductIds:
      - RHEL
      - RHEL for x86
      - RHEL Server
  - engProductId: 71 # Red Hat Enterprise Linux Workstation
    swatchProductIds:
      - RHEL
      - RHEL for x86
      - RHEL Workstation
  - engProductId: 72 # Red Hat Enterprise Linux for IBM z Systems
    swatchProductIds:
      - RHEL
      - RHEL for IBM z
  - engProductId: 74 # Red Hat Enterprise Linux for Power, big endian
    swatchProductIds:
      - RHEL
      - RHEL for IBM Power
  - engProductId: 76 # Red Hat Enterprise Linux for Scientific Computing
    swatchProductIds:
      - RHEL
      - RHEL for x86
      - RHEL Compute Node
  - engProductId: 279 # Red Hat Enterprise Linux for Power, little endian
    swatchProductIds:
      - RHEL
      - RHEL for IBM Power
  - engProductId: 419 # Red Hat Enterprise Linux for ARM 64
    swatchProductIds:
      - RHEL
      - RHEL for ARM
  - engProductId: 420 # Red Hat Enterprise Linux for Power 9
    swatchProductIds:
      - RHEL
      - RHEL for IBM Power
  - engProductId: 479 # Red Hat Enterprise Linux for x86_64 (RHEL8)
    swatchProductIds:
      - RHEL
      - RHEL for x86
finestGranularity: DAILY
burstable: false
syspurposeRoles:
  - name: Red Hat Enterprise Linux Server
    swatchProductIds:
      - RHEL
      - RHEL Server
  - name: Red Hat Enterprise Linux Workstation
    swatchProductIds:
      - RHEL
      - RHEL Workstation
  - name: Red Hat Enterprise Linux Compute Node
    swatchProductIds:
      - RHEL
      - RHEL Compute Node
architectureSwatchProductIdMap:
  aarch64: RHEL for ARM
  arm64: RHEL for ARM
  i386: RHEL for x86
  ppc64: RHEL for IBM Power
  ppc64le: RHEL for IBM Power
  s390x: RHEL for IBM z
  x86_64: RHEL for x86
---
name: SatelliteProducts
products:
  - engProductId: 250 # Red Hat Satellite
    swatchProductIds:
      - Satellite
      - Satellite Server
  - engProductId: 269 # Red Hat Satellite Capsule
    swatchProductIds:
      - Satellite
      - Satellite Capsule
finestGranularity: DAILY
burstable: false
syspurposeRoles: []
architectureSwatchProductIdMap: {}
---
# Profile for OpenShift sold as a product
name: OpenShiftContainerPlatform
products:
  - engProductId: 290 # Red Hat OpenShift Container Platform
    swatchProductIds:
      - OpenShift Container Platform
finestGranularity: DAILY
burstable: false
syspurposeRoles: []
architectureSwatchProductIdMap: {}
---
# Profile for pay-as-you-go OpenShift consumption
# The SKUs for OpenShiftMetrics do not have engineering product ids. Instead we rely on a syspurpose role
# being set to determine which Swatch product ID is applicable.
name: OpenShiftMetrics
products: []
syspurposeRoles:
  - name: ocp
    swatchProductIds:
      - OpenShift-metrics
  - name: osd
    swatchProductIds:
      - OpenShift-dedicated-metrics
serviceType: OpenShift Cluster
finestGranularity: HOURLY
defaultSla: PREMIUM
defaultUsage: PRODUCTION
burstable: false
architectureSwatchProductIdMap: {}
marketplaceMetrics:
  - metricId: redhat.com:openshiftdedicated:cpu_hour
    uom: Cores
    swatchProductIds:
      - OpenShift-dedicated-metrics
      # NOTE(khowell): remove when https://issues.redhat.com/browse/ENT-3737 is implemented
      - OpenShift-metrics
