---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: swatch-database
parameters:
  - name: IMAGE_PULL_SECRET
    value: quay-cloudservices-pull
  - name: ENV_NAME
    value: env-swatch-database

objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: swatch-database
    spec:
      envName: ${ENV_NAME}
      pullSecrets:
        name: ${IMAGE_PULL_SECRET}

      database:
        # From the Clowder documentation:
        # Defines the Name of the database used by this app. This will be used as the name of the
        # logical database created by Clowder when the DB provider is in (local) mode. In
        # (app-interface) mode, the name here is used to locate the DB secret as a fallback
        # mechanism in cases where there is no 'clowder/database: <app-name>' annotation set on
        # any secrets by looking for a secret with 'db.host' starting with '<name>-<env>' where
        # env is usually 'stage' or 'prod'

        # In our case, we want to fall back to the legacy name "swatch-tally".  Eventually, we
        # will rename the secret to swatch-database-db but that will be a subsequent step so that
        # we don't incur an outage
        name: swatch-tally
        version: 13
