---
version: '3.8'
services:
  prometheus:
    image: quay.io/redhat-services-prod/rh-subs-watch-tenant/prometheus:d426e7d
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:8000"
      - "127.0.0.1:9091:9000"
    volumes:
      - /tmp/prometheus-data:/var/lib/prometheus:Z