receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: DEBUG

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors:
      exporters: [logging]
