openapi: "3.0.2"
info:
  title: "rhsm-subscriptions internal billing API"
  version: 1.0.0

servers:
  - url: /api
  - url: https://{HOSTNAME}/api
    variables:
      HOSTNAME:
        enum:
          - ci.cloud.redhat.com
          - qa.cloud.redhat.com
          - stage.cloud.redhat.com
          - cloud.redhat.com
        default: ci.cloud.redhat.com

paths:
  /swatch-tally/internal/remittance/accountRemittances:
    description: 'Operations to get specific account remittances'
    parameters:
      - name: productId
        in: query
        required: true
        schema:
          type: string
      - name: orgId
        in: query
        required: false
        schema:
          type: string
      - name: metricId
        in: query
        required: false
        schema:
          type: string
      - name: billingProvider
        in: query
        required: false
        schema:
          type: string
      - name: billingAccountId
        in: query
        required: false
        schema:
          type: string
      - name: beginning
        in: query
        required: false
        schema:
          type: string
          format: date-time
      - name: ending
        in: query
        required: false
        schema:
          type: string
          format: date-time
    get:
      operationId: getRemittances
      summary: "Get all monthly remittances for an account"
      responses:
        '200':
          description: "Found Account Remittances."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountRemittances"
        '400':
          $ref: "../../../spec/error-responses.yaml#/$defs/BadRequest"
        '403':
          $ref: "../../../spec/error-responses.yaml#/$defs/Forbidden"
        '500':
          $ref: "../../../spec/error-responses.yaml#/$defs/InternalServerError"
      tags:
        - internalBilling
  /swatch-billing/internal/openapi.json:
    $ref: "../../../spec/openapi-paths.yaml#/openapi-json"
  /swatch-billing/internal/openapi:
    $ref: "../../../spec/openapi-paths.yaml#/openapi-yaml"

components:
  schemas:
    AccountRemittances:
      type: array
      items:
        $ref: "#/components/schemas/MonthlyRemittance"
    MonthlyRemittance:
      description: Encapsulates all Monthly remittance
      properties:
        orgId:
          type: string
        productId:
          type: string
        metricId:
          type: string
        billingProvider:
          type: string
        billingAccountId:
          type: string
        remittedValue:
          type: number
          format: double
        accumulationPeriod:
          type: string
        remittanceDate:
          type: string
          format: date-time
  securitySchemes:
    PskIdentity:
      type: apiKey
      in: header
      name: x-rh-swatch-psk
      description: |
        Psk header containing Pre Shared Key. Contains an
        UUID string:
        ```
        c9a98753-2092-4617-b226-5c2653330b3d
        ``` 

security:
  - PskIdentity: []
