openapi: "3.0.2"
info:
  title: "internal-subscriptions-sync-api"
  description: "REST interface for the internal-subscriptions-sync- service. Please note any deprecated APIs. Our current deprecation policy is to keep deprecated APIs around for at least 6 months."
  version: 1.0.0

servers:
  - url: /{PATH_PREFIX}/{APP_NAME}/v1
    variables:
      PATH_PREFIX:
        default: api
      APP_NAME:
        default: rhsm-subscriptions
  - url: https://{HOSTNAME}/{PATH_PREFIX}/{APP_NAME}/v1
    variables:
      HOSTNAME:
        enum:
          - ci.cloud.redhat.com
          - qa.cloud.redhat.com
          - stage.cloud.redhat.com
          - cloud.redhat.com
        default: ci.cloud.redhat.com
      PATH_PREFIX:
        default: api
      APP_NAME:
        default: rhsm-subscriptions

paths:
  /internal/subscriptions/sync/org/{org_id}:
    description: "Force sync of subscriptions for given org_id."
    parameters:
      - name: org_id
        in: path
        required: true
        schema:
          type: string
        description: "The ID for the organization subscriptions to sync"
    put:
      summary: "Sync all subscriptions for given org_id."
      operationId: forceSyncSubscriptionsForOrg
      tags:
        - internalSubscriptions
        - internal
      responses:
        '200':
          description: "The request for syncing organization's subscription was successful."
          content:
            text/plain:
              schema:
                type: string
                example: Success
        '400':
          $ref: "../../../spec/error-responses.yaml#/$defs/BadRequest"
        '403':
          $ref: "../../../spec/error-responses.yaml#/$defs/Forbidden"
        '404':
          $ref: "../../../spec/error-responses.yaml#/$defs/ResourceNotFound"
        '500':
          $ref: "../../../spec/error-responses.yaml#/$defs/InternalServerError"
  /internal-subscription-sync-openapi.json:
    $ref: "../../../spec/openapi-paths.yaml#/openapi-json"
  /internal-subscription-sync-openapi.yaml:
    $ref: "../../../spec/openapi-paths.yaml#/openapi-yaml"

components:
  securitySchemes:
    PskIdentity:
      type: apiKey
      in: header
      name: x-rh-swatch-psk
      description: |
        Psk header containing Pre Shared Key. Contains an
        UUID string:
        ```
        c9a98753-2092-4617-b226-5c2653330b3d
        ```

security:
  - PskIdentity: []
