openapi: "3.0.2"
info:
  title: "swatch-producer-red-hat-marketplace internal API"
  version: 1.0.0

servers:
  - url: /api
  - url: https://{HOSTNAME}/api
    variables:
      HOSTNAME:
        enum:
          - ci.cloud.redhat.com
          - qa.cloud.redhat.com
          - stage.cloud.redhat.com
          - cloud.redhat.com
        default: ci.cloud.redhat.com

paths:
  /swatch-producer-red-hat-marketplace/internal/rhm/status/{batch_id}:
    parameters:
      - name: batch_id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: "Fetch a usage event status for a given batch"
      operationId: getUsageEventStatus
      responses:
        '200':
          description: "Found a batch matching the id and was able to retrieve it's status"
          content:
            application/json:
              schema:
                $ref: "../../../clients/rh-marketplace-client/rh-marketplace-api-spec.yaml#/components/schemas/StatusResponse"
  /swatch-producer-red-hat-marketplace/internal/openapi.json:
    $ref: "../../../spec/openapi-paths.yaml#/openapi-json"
  /swatch-producer-red-hat-marketplace/internal/openapi:
    $ref: "../../../spec/openapi-paths.yaml#/openapi-yaml"
components:
  securitySchemes:
    PskIdentity:
      type: apiKey
      in: header
      name: x-rh-swatch-psk
      description: |
        Psk header containing Pre Shared Key. Contains an
        UUID string:
        ```
        c9a98753-2092-4617-b226-5c2653330b3d
        ```
security:
  - PskIdentity: []
