---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhsm
parameters:
  - name: IMAGE_PULL_SECRET
    value: quay-cloudservices-pull
  - name: ENV_NAME
    value: env-rhsm
  - name: IMAGE
    value: quay.io/cloudservices/rhsm-subscriptions
  - name: IMAGE_TAG
    value: latest

objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: rhsm
    spec:
      # The name of the ClowdEnvironment providing the services
      envName: ${ENV_NAME}
      # IQE plugin your ClowdApp is associated with
      testing:
        iqePlugin: rhsm-subscriptions

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: swatch-otel-config
    data:
      relay: |
        extensions:
          health_check:
            endpoint: 0.0.0.0:13133
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: 0.0.0.0:4317
              http:
                endpoint: 0.0.0.0:4318
        processors:
          batch:
        exporters:
          debug:
            verbosity: detailed
        service:
          extensions:
            - health_check
          pipelines:
            traces:
              receivers: [otlp]
              processors: [batch]
              exporters: [debug]
          telemetry:
            logs:
              level: info

  - apiVersion: v1
    kind: Secret
    metadata:
      name: signalfx
    type: Opaque
    data:
      # dummy-token for testing purposes only
      token: ZHVtbXktdG9rZW4=