---
apiVersion: v1
kind: Template
metadata:
  name: rhsm-post-deployment-tests
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    name: rhsm-post-deployment-tests-${IMAGE_TAG}-${UID}
  spec:
    appName: rhsm
    testing:
      iqe:
        debug: false
        dynaconfEnvName: stage_post_deploy
        filter: ''
        marker: 'post_stage_deploy'
        plugins: "rhsm_subscriptions"
parameters:
- name: IMAGE_TAG
  value: ''
  required: true
- name: UID
  description: "Unique CJI name suffix"
  generate: expression
  from: "[a-z0-9]{6}"
