{
 "title": "Subscription Watch",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "rdsdatasource", "query": "cloudwatch" }
  ]
 },
 "panels": [
  {
   "title": "DB Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB CPU usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "rhsm-prod",
       "dimensions": { "DBInstanceIdentifier": "rhsm-prod" },
       "metricName": "CPUUtilization",
       "namespace": "AWS/RDS",
       "region": "default",
       "statistic": "Average"
      },
      {
       "alias": "rhsm-stage",
       "dimensions": { "DBInstanceIdentifier": "rhsm-stage" },
       "metricName": "CPUUtilization",
       "namespace": "AWS/RDS",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "DB Free Space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "rhsm-prod",
       "dimensions": { "DBInstanceIdentifier": "rhsm-prod" },
       "metricName": "FreeStorageSpace",
       "namespace": "AWS/RDS",
       "region": "default",
       "statistic": "Average"
      },
      {
       "alias": "rhsm-stage",
       "dimensions": { "DBInstanceIdentifier": "rhsm-stage" },
       "metricName": "FreeStorageSpace",
       "namespace": "AWS/RDS",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "DB IOPs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "rhsm-prod read iops avg",
       "dimensions": { "DBInstanceIdentifier": "rhsm-prod" },
       "metricName": "ReadIOPS",
       "namespace": "AWS/RDS",
       "region": "default",
       "statistic": "Average"
      },
      {
       "alias": "rhsm-prod write iops avg",
       "dimensions": { "DBInstanceIdentifier": "rhsm-prod" },
       "metricName": "WriteIOPS",
       "namespace": "AWS/RDS",
       "region": "default",
       "statistic": "Average"
      },
      {
       "alias": "rhsm-stage read iops avg",
       "dimensions": { "DBInstanceIdentifier": "rhsm-stage" },
       "metricName": "ReadIOPS",
       "namespace": "AWS/RDS",
       "region": "default",
       "statistic": "Average"
      },
      {
       "alias": "rhsm-stage write iops avg",
       "dimensions": { "DBInstanceIdentifier": "rhsm-stage" },
       "metricName": "WriteIOPS",
       "namespace": "AWS/RDS",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "DB Freeable Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "rhsm-prod",
       "dimensions": { "DBInstanceIdentifier": "rhsm-prod" },
       "metricName": "FreeableMemory",
       "namespace": "AWS/RDS",
       "region": "default",
       "statistic": "Average"
      },
      {
       "alias": "rhsm-stage",
       "dimensions": { "DBInstanceIdentifier": "rhsm-stage" },
       "metricName": "FreeableMemory",
       "namespace": "AWS/RDS",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "System Conduit (rhsm-conduit)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "HBI Host Create/Update Stats",
     "type": "stat",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(inventory_ingress_add_host_failures_total{reporter=\"rhsm-conduit\"}[$__range]))",
       "legendFormat": "failures"
      },
      {
       "expr": "sum(increase(inventory_ingress_add_host_successes_total{reporter=\"rhsm-conduit\"}[$__range])) by (result)",
       "legendFormat": "{{ result }}"
      }
     ]
    },
    {
     "title": "rhsm-conduit consumer group lag",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_group_lag{topic='platform.rhsm-conduit.tasks'}) by (topic)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ topic }} consumer group lag",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HBI host production rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "message/sec" }
     ],
     "targets": [
      {
       "expr": "rate(rhsm_conduit_send_inventory_message_total[$__interval])"
      }
     ]
    },
    {
     "title": "rhsm-conduit max sync duration",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(rhsm_subscriptions_task_execution_seconds_max{job=\"rhsm-conduit\"}) by (deployment)",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "rhsm-conduit topic consumption rate (orgs/second)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none", "label": "orgs/sec" }
     ],
     "targets": [
      {
       "expr": "sum by (topic) (rate(kafka_consumergroup_group_offset{topic='platform.rhsm-conduit.tasks'}[$__interval]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ topic }}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "rhsm-conduit CPU",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(process_cpu_usage{service=\"rhsm-conduit\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "JVM Memory Used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (id, pod) (jvm_memory_used_bytes{service=\"rhsm-conduit\"})",
       "legendFormat": "{{ id }} {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tally",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "subscriptions-jobs consumer group lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_group_lag{topic='platform.rhsm-subscriptions.tasks'})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "platform.rhsm-subscriptions.tasks consumer group lag",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "subscriptions-jobs org rate (orgs/sec)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_consumergroup_group_offset{topic=\"platform.rhsm-subscriptions.tasks\"}[$__interval]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "orgs/sec",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "rhsm-subscriptions worker CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(process_cpu_usage{service=~\"rhsm-subscriptions-worker-monitoring|rhsm-subscriptions-scheduler-monitoring\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      },
      { "expr": "process" }
     ]
    },
    {
     "title": "worker JVM Memory Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service=~\"rhsm-subscriptions-worker-monitoring|rhsm-subscriptions-scheduler-monitoring\",id=~\"PS Old Gen|PS Survivor Space|PS Eden Space\"}",
       "legendFormat": "{{ pod }} {{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "APIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "API request rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (uri) (rate(http_server_requests_seconds_count{service=\"rhsm-subscriptions\",uri=~\"/api/rhsm-subscriptions.*\"}[1m]))",
       "legendFormat": "{{ uri }}"
      }
     ]
    },
    {
     "title": "request latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "s", "label": "time per batch" }
     ],
     "targets": [
      {
       "expr": "sum by (uri) (rate(http_server_requests_seconds_sum{service=\"rhsm-subscriptions\",uri=~\"/api/rhsm-subscriptions.*\"}[1m]) / rate(http_server_requests_seconds_count{service=\"rhsm-subscriptions\",uri=~\"/api/rhsm-subscriptions.*\"}[1m]))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{service=\"rhsm-subscriptions\",exception!=\"None\"}[$__interval])"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(process_cpu_usage{service=\"rhsm-subscriptions\"}) by (pod)",
       "legendFormat": "{{ kubernetes_pod_name }}"
      }
     ]
    },
    {
     "title": "JVM Memory Used",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (id, pod) (jvm_memory_used_bytes{service=\"rhsm-subscriptions\"})",
       "legendFormat": "{{ id }} {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Capacity Ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "subscription-ingress batch rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Batches / Second" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"/api/rhsm-subscriptions/v1/ingress/candlepin_pools/.*\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "subscription-ingress latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "s", "label": "time per batch" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{uri=~\"/api/rhsm-subscriptions/v1/ingress/candlepin_pools/.*\"}[$__interval])) / sum(rate(http_server_requests_seconds_count{uri=~\"/api/rhsm-subscriptions/v1/ingress/candlepin_pools/.*\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{uri=\"/api/rhsm-subscriptions/v1/ingress/candlepin_pools/.*\",exception!=\"None\"}[1m])"
      }
     ]
    }
   ]
  },
  { "title": "Billing Provider Integration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "OpenShift Metering Task Lag",
   "type": "graph",
   "description": "⬇️ OCM provides usage metrics that are read by the metering collector job ⬇️\n\n(TIP: if this isn't working, data will not land in swatch DB at all)",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=\"platform.rhsm-subscriptions.metering-tasks\"}) by (group, partition)",
     "legendFormat": "partition {{ partition }}"
    }
   ]
  },
  {
   "title": "Tally Task Lag",
   "type": "graph",
   "description": "⬇️ Sampled metrics stored in DB are \"collapsed\" into summary metrics ⬇️\n\n(TIP: Summary metrics are displayed in web UI)",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=\"platform.rhsm-subscriptions.tasks\"}) by (group, partition)",
     "legendFormat": "partition {{ partition }}"
    }
   ]
  },
  {
   "title": "Tally to Billable Usage Lag",
   "type": "graph",
   "description": "rhsm-subscriptions-worker service produces TallySummary messages for consumption by Billing Usage service",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=\"platform.rhsm-subscriptions.tally\", group=\"swatch-producer-billing\"}) by (group, partition)",
     "legendFormat": "partition {{ partition }}"
    }
   ]
  },
  {
   "title": "AWS Billable Usage Lag",
   "type": "graph",
   "description": "Billable Usage service emits messages with usage data for swatch billing provider services to consume.  This widget monitors the consumer group connected to the swatch-producer-aws service)",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=\"platform.rhsm-subscriptions.billable-usage\", group=\"swatch-producer-aws\"}) by (group, partition)",
     "legendFormat": "partition {{ partition }}"
    }
   ]
  },
  {
   "title": "RH Marketplace Billable Usage Lag",
   "type": "graph",
   "description": "Billable Usage service emits messages with usage data for swatch billing provider services to consume.  This widget monitors the rh-marketplace-worker consumer group (consumed by the swatch-billing-provider-rh-marketplace service)",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=\"platform.rhsm-subscriptions.billable-usage\", group=\"swatch-producer-rh-marketplace\"}) by (group, partition)",
     "legendFormat": "partition {{ partition }}"
    }
   ]
  },
  {
   "title": "Red Hat Marketplace Batch Stats",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(rhsm_subscriptions_rh_marketplace_batch_accepted_total[$__range]))",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(increase(rhsm_subscriptions_rh_marketplace_batch_rejected_total[$__range]))",
     "legendFormat": "rejected"
    },
    {
     "expr": "sum(increase(rhsm_subscriptions_rh_marketplace_batch_unverified_total[$__range]))",
     "legendFormat": "unverified"
    }
   ]
  }
 ]
}