<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>com.redhat.swatch</groupId>
    <artifactId>swatch-parent</artifactId>
    <version>1.1.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <modelVersion>4.0.0</modelVersion>
  <artifactId>swatch-component-tests-parent</artifactId>
  <name>SWATCH - Parent - Component Tests</name>
  <packaging>pom</packaging>

  <properties>
    <swatch.ct.metadata.component />
    <swatch.ct.metadata.git_revision />
    <swatch.ct.metadata.pipeline_name />
    <swatch.ct.metadata.event_type />
    <swatch.ct.metadata.integration_test_name />
    <swatch.ct.metadata.env>ephemeral</swatch.ct.metadata.env>
    <swatch.ct.metadata.tool>konflux</swatch.ct.metadata.tool>
    <swatch.ct.metadata.source />
  </properties>

  <modules>
    <module>../swatch-test-framework</module>
    <module>../swatch-test-hbi-support</module>
  </modules>

  <dependencies>
    <dependency>
      <groupId>com.redhat.swatch</groupId>
      <artifactId>swatch-test-framework</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>component-tests</id>
      <modules>
        <module>../swatch-utilization/ct</module>
        <module>../swatch-contracts/ct</module>
        <module>../swatch-producer-azure/ct</module>
        <module>../swatch-producer-aws/ct</module>
        <module>../swatch-metrics-hbi/ct</module>
        <module>../swatch-metrics/ct</module>
        <module>../swatch-tally/ct</module>
        <module>../swatch-billable-usage/ct</module>
        <module>../swatch-system-conduit/ct</module>
      </modules>
    </profile>
  </profiles>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <systemPropertyVariables>
            <component>${swatch.ct.metadata.component}</component>
            <git_revision>${swatch.ct.metadata.git_revision}</git_revision>
            <pipeline_name>${swatch.ct.metadata.pipeline_name}</pipeline_name>
            <event_type>${swatch.ct.metadata.event_type}</event_type>
            <integration_test_name>${swatch.ct.metadata.integration_test_name}</integration_test_name>
            <env>${swatch.ct.metadata.env}</env>
            <tool>${swatch.ct.metadata.tool}</tool>
            <source>${swatch.ct.metadata.source}</source>
          </systemPropertyVariables>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>add-ct-sources</id>
            <phase>generate-test-sources</phase>
            <goals>
              <goal>add-test-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${project.basedir}/java</source>
                <source>${project.basedir}/target/generated-sources/src/main/java</source>
              </sources>
            </configuration>
          </execution>
          <execution>
            <id>add-ct-resources</id>
            <phase>generate-test-resources</phase>
            <goals>
              <goal>add-test-resource</goal>
            </goals>
            <configuration>
              <resources>
                <resource>
                  <directory>${project.basedir}/resources</directory>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
