---
apiVersion: v1
kind: Template
metadata:
  name: catalog-inventory
objects:
- apiVersion: v1
  kind: Secret # For ephemeral/local environment
  metadata:
    name: catalog-inventory-secrets
    labels:
      app: catalog-inventory
  stringData:
    encryption-key: "${ENCRYPTION_KEY}"
    secret-key: "${SECRET_KEY}"

- apiVersion: v1
  kind: Secret
  metadata:
    name: catalog-inventory-psk
    labels:
      app: catalog-inventory
  stringData:
    client-psk: "${CLOUD_CONTROLLER_PSK}"

- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: catalog-inventory
  spec:
    envName: ${ENV_NAME}
    deployments:
    - name: api
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true
      podSpec:
        initContainers: #TODO
        image: ${IMAGE}:${IMAGE_TAG}
        env:
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: catalog-inventory-secrets
              key: encryption-key
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: catalog-inventory-secrets
              key: secret-key
        - name: CLOUD_CONTROLLER_PSK
          valueFrom:
            secretKeyRef:
              name: catalog-inventory-psk
              key: client-psk

        - name: SOURCES_URL
          value: ${SOURCES_SCHEME}://${SOURCES_HOST}:${SOURCES_PORT}
        - name: CURRENT_API_VERSION
          value: ${CURRENT_API_VERSION}
        - name: CLOUD_CONNECTOR_URL
          value: ${CLOUD_CONNECTOR_SCHEME}://${CLOUD_CONNECTOR_HOST}:${CLOUD_CONNECTOR_PORT}
        - name: CATALOG_INVENTORY_INTERNAL_URL
          value: ${CATALOG_INVENTORY_SCHEME}://${CATALOG_INVENTORY_HOST}:${CATALOG_INVENTORY_PORT}
        - name: CATALOG_INVENTORY_EXTERNAL_URL
          value: https://cert.${CATALOG_INVENTORY_EXTERNAL_HOST}/api/catalog-inventory # Temp to add cert here
        - name: UPLOAD_URL
          value: https://cert.${CATALOG_INVENTORY_EXTERNAL_HOST}/api/ingress/v1/upload
        - name: RAILS_LOG_LEVEL
          value: ${LOG_LEVEL}
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        - name: INACTIVE_TASK_REMINDER_TIME
          value: ${INACTIVE_TASK_REMINDER_TIME}
        - name: SOURCE_REFRESH_TIMEOUT
          value: ${SOURCE_REFRESH_TIMEOUT}
        readinessProbe:
          tcpSocket:
            port: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: 200m
            memory: 256Mi
    jobs:
    - name: cleanup-tasks
      schedule: ${CLEANUP_SCHEDULE}
      concurrencyPolicy: Forbid
      restartPolicy: Never
      startingDeadlineSeconds: 30
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command:
        - bin/cleanup_tasks
        env:
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: catalog-inventory-secrets
              key: encryption-key
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: catalog-inventory-secrets
              key: secret-key
        - name: LOG_LEVEL
          value: ${LOG_LEVEL}
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: 200m
            memory: 256Mi
    kafkaTopics:
    - replicas: 3
      partitions: 3
      topicName: platform.sources.event-stream
    - replicas: 3
      partitions: 3
      topicName: platform.topological-inventory.operations-ansible-tower
    - replicas: 3
      partitions: 3
      topicName: platform.upload.catalog
    - replicas: 3
      partitions: 10
      topicName: platform.catalog.persister
    - replicas: 3
      partitions: 3
      topicName: platform.sources.status
    - replicas: 3
      partitions: 3
      topicName: platform.catalog-inventory.task-output-stream
    dependencies:
    - ingress
    - sources-api
    database:
      name: catalog-inventory

parameters:
- name: CURRENT_API_VERSION
  value: v1.0
- name: INACTIVE_TASK_REMINDER_TIME
  value: "30"
- name: SOURCE_REFRESH_TIMEOUT
  value: "10"
- name: CHECK_AVAILABILITY_TIMEOUT
  value: "10"
- name: LOG_LEVEL
  value: INFO
- description: Cpu limit of service
  name: CPU_LIMIT
  value: 500m
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 512Mi
- name: MIN_REPLICAS
  value: '3'
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Image name
  name: IMAGE
  value: quay.io/cloudservices/catalog_inventory-api
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "true"
- description: ClowdEnv Name
  name: ENV_NAME
  required: false
- name: ENCRYPTION_KEY
  displayName: Encryption Key (Ephemeral)
  required: true
  description: Encryption Key for Passwords
  from: "[a-zA-Z0-9]{43}"
  generate: expression
- name: SECRET_KEY
  displayName: Secret Key (Ephemeral)
  required: true
  description: Rails SECRET_KEY_BASE
  from: "[a-f0-9]{128}"
  generate: expression
- name: CLOUD_CONTROLLER_PSK
  displayName: Pre Shared Key for Cloud Controller
  required: true
  description: Pre Shared Key
  from: "[a-f0-9]{128}"
  generate: expression
- description: Schedule to cleanup tasks
  displayName: Schedule to cleanup tasks
  name: CLEANUP_SCHEDULE
  value: "0 0 * * *"
- description: Host to use for the Sources service URL.
  displayName: Sources Service Host
  name: SOURCES_HOST
  value: sources-api-svc
- description: Port to use for the Sources service URL.
  displayName: Sources Service Port
  name: SOURCES_PORT
  required: true
  value: '8000'
- description: Scheme to use for the Sources service URL. Can be either http or https
  displayName: Sources Service Scheme
  name: SOURCES_SCHEME
  required: true
  value: http
- description: Port to use for the Cloud Connector service URL.
  displayName: Cloud Connector Service Port
  name: CLOUD_CONNECTOR_PORT
  required: true
  value: '8080'
- description: Scheme to use for the Cloud Connector service URL. Can be either http or https
  displayName: Cloud Connector Service Scheme
  name: CLOUD_CONNECTOR_SCHEME
  required: true
  value: http
- description: Host to use for the Cloud Connector service URL.
  displayName: Cloud Connector Service URL
  name: CLOUD_CONNECTOR_HOST
  value: cloud-connector
- description: Port to use for the internal Catalog Inventory service URL.
  displayName: Internal Catalog Inventory Service Port
  name: CATALOG_INVENTORY_PORT
  required: true
  value: '8080'
- description: Scheme to use for the internal Catalog Inventory service URL. Can be either http or https
  displayName: Internal Catalog Inventory Service Scheme
  name: CATALOG_INVENTORY_SCHEME
  required: true
  value: http
- description: Host to use for the internal Catalog Inventory service URL.
  displayName: Internal Catalog Inventory Service URL
  name: CATALOG_INVENTORY_HOST
  value: catalog-inventory-api
- description: Host to use for the external Catalog Inventory service URL.
  displayName: External Catalog Inventory Service URL
  name: CATALOG_INVENTORY_EXTERNAL_HOST
  value: cloud.stage.redhat.com