---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: wiremock
parameters:
  - name: ENV_NAME
    value: env-wiremock
  - name: IMAGE
    value: docker.io/wiremock/wiremock
  - name: IMAGE_TAG
    value: 3.9.1
  - name: MEMORY_REQUEST
    value: 1000Mi
  - name: MEMORY_LIMIT
    value: 1400Mi
  - name: CPU_REQUEST
    value: 350m
  - name: CPU_LIMIT
    value: 1500m
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: wiremock
      labels:
        app: wiremock
    spec:
      envName: ${ENV_NAME}

      deployments:
        - name: service
          replicas: 1
          webServices:
            public:
              enabled: true
          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
            resources:
              requests:
                cpu: ${CPU_REQUEST}
                memory: ${MEMORY_REQUEST}
              limits:
                cpu: ${CPU_LIMIT}
                memory: ${MEMORY_LIMIT}
            env:
              - name: WIREMOCK_OPTIONS
                value: --port=8000
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /__admin/health
                port: 8000
                scheme: HTTP
              initialDelaySeconds: 20
              periodSeconds: 20
              successThreshold: 1
              timeoutSeconds: 5
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /__admin/health
                port: 8000
                scheme: HTTP
              initialDelaySeconds: 20
              periodSeconds: 20
              successThreshold: 1
              timeoutSeconds: 5