openapi: "3.0.2"
info:
  title: "pinhead-client-api"
  description: "REST interface for the pinhead client used by rhsm-conduit"
  version: 1.0.0

servers:
  - url: https://localhost/

paths:
  /owners/{orgId}/consumers/feed:
    description: "Consumer operations based on an owner."
    parameters:
      - name: orgId
        in: path
        required: true
        schema:
          type: string
        description: "The orgId is the candlepin owner key."
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
        description: "Number of consumers to emit at once."
      - name: offset
        in: query
        required: false
        schema:
          type: string
        description: "Paging offset."
      - name: last_checkin_after
        in: query
        required: false
        schema:
          type: string
          pattern: '^([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T(0[0-9]|1[0-9]|2[1-4]):(0[0-9]|[1-5][0-9]):(0[0-9]|[1-5][0-9]))Z$'
        description: "Last check in time in YYYY-MM-DDTHH-MM-SSZ format"
    get:
      description: "List consumers on an owner."
      operationId: getConsumersForOrg
      tags:
        - pinhead
      responses:
        '200':
          description: "The request for consumer data was successful."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrgInventory"
        '400':
          $ref: "#/components/responses/BadRequest"
        '404':
          $ref: "#/components/responses/ResourceNotFound"
        '500':
          $ref: "#/components/responses/InternalServerError"
components:
  responses:
    InternalServerError:
      description: "An internal server error has occurred and is not recoverable."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    BadRequest:
      description: "The server could could not process the current request."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    ResourceNotFound:
      description: "The requested resource was not found."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    Consumer:
      required:
        - uuid
        - name
        - orgId
        - lastCheckin
        - consumerType
        - installedProducts
        - sysPurposeRole
        - sysPurposeUsage
        - sysPurposeAddons
        - facts
      properties:
        type:
          type: string
        uuid:
          type: string
        name:
          type: string
        orgId:
          type: string
        accountNumber:
          type: string
        lastCheckin:
          type: string
          format: date-time
        consumerType:
          type: string
        installedProducts:
          type: array
          items:
            $ref: "#/components/schema/InstalledProducts"
        serviceLevel:
          type: string
        sysPurposeRole:
          type: string
        sysPurposeUsage:
          type: string
        sysPurposeAddons:
          type: array
          items:
            type: string
        facts:
          type: object
          additionalProperties:
            type: string
        hypervisorUuid:
          type: string
        hypervisorName:
          type: string
        guestId:
          type: string

    InstalledProducts:
      required:
        - productId
        - productName
        - productVersion
      properties:
        productId:
          type: integer
          format: int64
        productName:
          type: string
        productVersion:
          type: string

    Status:
      required:
        - code
        - message
        - pagination
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
        pagination:
          $ref: "#/components/schemas/Pagination"

    Pagination:
      required:
        - firstId
        - lastId
        - nextOffset
        - totalCount
        - displayedCount
      properties:
        firstId:
          type: string
        lastId:
          type: string
        nextOffset:
          type: string
        currentOffset:
          type: string
        totalCount:
          type: integer
          format: int64
        displayCount:
          type: integer
          format: int64

    OrgInventory:
      properties:
        status:
          $ref: "#/components/schemas/Status"
        feeds:
          type: array
          items:
            $ref: "#/components/schemas/Consumer"

