# This is a file maintained by the rhsm-subscription project that describes
# a portion of the Red Hat IT Subscriptions API.
openapi: "3.0.2"
info:
  title: "subscription-api"
  description: "Third-party specification for Subscription API"
  version: 1.0.0

paths:
  /id={id}/options/options;products=ALL/:
    description: "Get a subscription by ID"
    parameters:
      - name: id
        required: true
        in: path
        description: "The ID of the subscription entity"
        schema:
          type: string
    get:
      summary: "Get a single subscription"
      operationId: "getSubscriptionById"
      tags:
        - search
      responses:
        '200':
          description: "The operation completed successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subscription"
  /search/criteria;subscription_number={subscriptionNumber}/options;products=ALL;showExternalReferences=true/:
    description: "Find a subscription by subscription number"
    parameters:
      - name: subscriptionNumber
        required: true
        in: path
        description: "The ID of the subscription entity"
        schema:
          type: string
    get:
      summary: "Get a single subscription"
      operationId: "getSubscriptionBySubscriptionNumber"
      tags:
        - search
      responses:
        '200':
          description: "The operation completed successfully"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Subscription"
  /search/criteria;web_customer_id={orgId}/options;products=ALL;showExternalReferences=true;firstResultIndex={index};maxResults={pageSize}/:
    description: "Search subscriptions on owner, index, and pageSize"
    parameters:
      - name: orgId
        required: true
        in: path
        description: "The web customer ID of the org"
        schema:
          type: string
      - name: index
        required: true
        in: path
        description: "The starting index of results"
        schema:
          type: integer
      - name: pageSize
        required: true
        in: path
        description: "The number of results per page"
        schema:
          type: integer
    get:
      summary: "List the requested data"
      operationId: "SearchSubscriptionsByOrgId"
      tags:
        - search
      responses:
        '200':
          description: "The operation completed successfully"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Subscription"

components:
  schemas:
    Subscription:
      required:
        - id
        - subscriptionNumber
        - subscriptionProducts
        - webCustomerId
        - quantity
      properties:
        id:
          type: integer
        subscriptionNumber:
          type: string
        quantity:
          type: integer
        webCustomerId:
          type: integer
        effectiveStartDate:
          type: integer
          format: int64
          description: The effective start date in epoch millisecond format.
        effectiveEndDate:
          type: integer
          format: int64
          description: The effective end date in epoch millisecond format.
        subscriptionProducts:
          type: array
          items:
            $ref: "#/components/schemas/SubscriptionProduct"
        externalReferences:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/ExternalReference"
    SubscriptionProduct:
      required:
        - sku
      properties:
        sku:
          type: string
        parentSubscriptionProductId:
          type: integer
    ExternalReference:
      properties:
        accountID:
          type: string
        subscriptionID:
          type: string
        customerID:
          type: string
        productCode:
          type: string
        sellerAccount:
          type: string
        customerAccountID:
          type: string
