apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: bonfire-component-tests-pipelinerun-
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/RedHatInsights/rhsm-subscriptions.git"
      - name: revision
        value: "main"
      - name: pathInRepo
        value: .tekton/bonfire-component-tests-pipeline.yaml
  params:
    # Bonfire configuration
    - name: BONFIRE_REPO
      value: "https://github.com/RedHatInsights/bonfire-tekton"
    - name: BONFIRE_REVISION
      value: "main"
    - name: BONFIRE_IMAGE
      value: "quay.io/redhat-services-prod/hcm-eng-prod-tenant/cicd-tools:3a72fea"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi