apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: bonfire-component-tests-pipelinerun-
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/RedHatInsights/rhsm-subscriptions.git"
      - name: revision
        value: "jcarvaja/SWATCH-3838"
      - name: pathInRepo
        value: .tekton/bonfire-component-tests-pipeline.yaml
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi