apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-tests
spec:
  params:
    - name: SERVICE
      description: The service to be tested. By default, it will run all the tests.
  workspaces:
    - name: source
  steps:
    - name: tests
      image: registry.access.redhat.com/ubi9/openjdk-17-runtime
      workingDir: $(workspaces.source.path)/source
      script: |
        #!/bin/bash
        if [ -n "$SERVICE" ]; then
          SUBMODULE="-pl ${SERVICE} -am"
        fi
        ./mvnw verify ${SUBMODULE}