kind: Pipeline
apiVersion: tekton.dev/v1
metadata:
  name: verify-snapshot-components
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
  tasks:
    - name: verify-snapshot-components
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/RedHatInsights/rhsm-subscriptions
          - name: revision
            value: main
          - name: pathInRepo
            value: .tekton/verify-snapshot-components-task.yaml