
quarkus.log.level=INFO
quarkus.banner.enabled=false

quarkus.liquibase.core.migrate-at-start=true
quarkus.liquibase.core.change-log=liquibase/changelog.xml

quarkus.liquibase.contracts.migrate-at-start=true
quarkus.liquibase.contracts.change-log=db/changelog.xml
quarkus.liquibase.contracts.database-change-log-lock-table-name=DATABASECHANGELOGLOCK_SWATCH_CONTRACTS
quarkus.liquibase.contracts.database-change-log-table-name=DATABASECHANGELOG_SWATCH_CONTRACTS

quarkus.datasource.core.db-kind=postgresql
quarkus.datasource.core.username=${DATABASE_USERNAME}
quarkus.datasource.core.password=${DATABASE_PASSWORD}
quarkus.datasource.core.jdbc.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DATABASE}

%dev.quarkus.datasource.core.username=rhsm-subscriptions
%dev.quarkus.datasource.core.password=rhsm-subscriptions
%dev.quarkus.datasource.core.jdbc.url=jdbc:postgresql://localhost:5432/rhsm-subscriptions

quarkus.datasource.contracts.db-kind=postgresql
quarkus.datasource.contracts.username=${DATABASE_USERNAME}
quarkus.datasource.contracts.password=${DATABASE_PASSWORD}
quarkus.datasource.contracts.jdbc.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DATABASE}

%dev.quarkus.datasource.contracts.username=rhsm-subscriptions
%dev.quarkus.datasource.contracts.password=rhsm-subscriptions
%dev.quarkus.datasource.contracts.jdbc.url=jdbc:postgresql://localhost:5432/rhsm-subscriptions

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DATABASE_USERNAME}
quarkus.datasource.password=${DATABASE_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DATABASE}

%dev.quarkus.datasource.username=rhsm-subscriptions
%dev.quarkus.datasource.password=rhsm-subscriptions
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/rhsm-subscriptions
