@startuml
!include <C4/C4_Container>

' see https://forum.plantuml.net/8356/white-backgrounds-are-rendered-transparent-in-svg
skinparam backgroundColor #FEFEFE

LAYOUT_WITH_LEGEND()

title Container diagram for Subscription watch Billing Producers

Person(customer, "Red Hat Customer")

Boundary(crc, console.redhat.com) {
  Boundary(swatch, "Subscription watch") {
    System(tally, "Tally", "System that tallies system usage based on telemetry.")
    ContainerQueue(tally_summaries, "platform.rhsm-subscriptions.tally", "Kafka Topic")
    System_Boundary(billing_producers, "Billing Producers") {
      Container(marketplace_worker, "RH Marketplace Worker", "Java, Container", "Notifies RH Marketplace of hourly usage.")
    }
  }
}

System_Ext(rh_marketplace, "marketplace.redhat.com", "Service responsible for billing the customer for PAYG usage.")

' tally process
Rel(tally, tally_summaries, "Produces to")

' marketplace notification
Rel_Back(tally_summaries, marketplace_worker, "Consumes from")
Rel(marketplace_worker, rh_marketplace, "Notifies", "JSON/HTTPS")

Rel(customer, rh_marketplace, "Uses", "HTTPS")
@enduml
