swatch.component-tests.services.kafkaBridge.log.enabled=false
swatch.component-tests.services.wiremock.log.enabled=false
swatch.component-tests.services.swatch-producer-aws.quarkus.expected-log=is configured to poll records from
