# This is a file maintained by the rhsm-subscription project that describes
# a portion of the Cloudigrade API.
openapi: "3.0.2"
info:
  title: "cloudigrade-api"
  description: "Third-party specification for Cloudigrade API"
  version: 1.0.0

paths:
  /concurrent/:
    description: "Operations on concurrent usages"
    parameters:
    - name: x-rh-identity
      required: true
      in: header
      description: "Account identity to query"
      schema:
        type: string
    - name: limit
      required: false
      in: query
      description: "Number of results to return per page."
      schema:
        type: integer
    - name: offset
      required: false
      in: query
      description: "The initial index from which to return the results."
      schema:
        type: integer
    - name: start_date
      required: false
      in: query
      schema:
        type: string
        format: date
    - name: end_date
      required: false
      in: query
      schema:
        type: string
        format: date
    get:
      summary: "List daily concurrent usages"
      operationId: "ListDailyConcurrentUsages"
      tags:
        - concurrent
      responses:
        '200':
          description: "The operation completed successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcurrencyReport'

components:
  schemas:
    ConcurrencyReport:
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/ConcurrentUsage"
        links:
          type: object
          properties:
            first:
              type: string
            last:
              type: string
            previous:
              type: string
            next:
              type: string
          required:
            - first
            - previous
            - last
            - next
        meta:
          type: object
          properties:
            count:
              type: integer
    ConcurrentUsage:
      required:
        - date
        - maximum_counts
      properties:
        date:
          type: string
          format: date
        maximum_counts:
          type: array
          items:
            $ref: '#/components/schemas/UsageCount'
    UsageCount:
      required:
        - arch
        - instances_count
        - role
        - sla
      properties:
        arch:
          type: string
        instances_count:
          type: integer
        role:
          type: string
        sla:
          type: string
        usage:
          type: string
    IdentityHeader:
      required:
        - identity
      properties:
        identity:
          type: object
          required:
            - account_number
            - user
          properties:
            account_number:
              type: string
            user:
              type: object
              required:
                - is_org_admin
              properties:
                is_org_admin:
                  type: boolean