{
 "title": "Subscription Watch - Component Resource Utilization",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (container, namespace) (\n  kube_pod_container_resource_requests{resource=\"cpu\", namespace =~ \"rhsm-stage|rhsm-prod\"} * 1000\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (container, namespace) (\n  kube_pod_container_resource_limits{resource=\"cpu\", namespace =~ \"rhsm-stage|rhsm-prod\"} * 1000\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (container,namespace) (\n  avg_over_time(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{\n      cluster = \"\",\n      namespace =~ \"rhsm-stage|rhsm-prod\"\n    }[14d:]\n  ) * 1000\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (container,namespace) (\nmax_over_time(\nnode_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{\ncluster = \"\",\nnamespace =~ \"rhsm-stage|rhsm-prod\"\n}[14d:]\n) * 1000\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "Configured Quota Requests & Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Resource Request",
     "type": "table",
     "gridPos": { "h": 9, "w": 10, "x": 1, "y": 2 },
     "targets": [
      {
       "expr": "max by (container, namespace) (\n  kube_pod_container_resource_requests{resource=\"cpu\", namespace =~ \"rhsm-stage|rhsm-prod\"} * 1000\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Resource Limit",
     "type": "table",
     "gridPos": { "h": 9, "w": 10, "x": 11, "y": 2 },
     "targets": [
      {
       "expr": "max by (container, namespace) (\n  kube_pod_container_resource_limits{resource=\"cpu\", namespace =~ \"rhsm-stage|rhsm-prod\"} * 1000\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mem Resource Request",
     "type": "table",
     "gridPos": { "h": 9, "w": 10, "x": 1, "y": 20 },
     "targets": [
      {
       "expr": "max by (container, namespace) (\n  kube_pod_container_resource_requests{resource=\"memory\", namespace =~ \"rhsm-stage|rhsm-prod\"} / (1024*1024)\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mem Resource Limit",
     "type": "table",
     "gridPos": { "h": 9, "w": 10, "x": 11, "y": 20 },
     "targets": [
      {
       "expr": "max by (container, namespace) (\n  kube_pod_container_resource_limits{resource=\"memory\", namespace =~ \"rhsm-stage|rhsm-prod\"} / (1024*1024)\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVG CPU",
     "type": "table",
     "gridPos": { "h": 9, "w": 10, "x": 1, "y": 3 },
     "targets": [
      {
       "expr": "avg by (container,namespace) (\n  avg_over_time(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{\n      cluster = \"\",\n      namespace =~ \"rhsm-stage|rhsm-prod\"\n    }[14d:]\n  ) * 1000\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max CPU",
     "type": "table",
     "gridPos": { "h": 9, "w": 10, "x": 11, "y": 3 },
     "targets": [
      {
       "expr": "max by (container,namespace) (\nmax_over_time(\nnode_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{\ncluster = \"\",\nnamespace =~ \"rhsm-stage|rhsm-prod\"\n}[14d:]\n) * 1000\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVG Memory",
     "type": "table",
     "gridPos": { "h": 9, "w": 10, "x": 1, "y": 30 },
     "targets": [
      {
       "expr": "avg by (container,namespace) (\n  avg_over_time(\n    container_memory_working_set_bytes{\n      cluster = \"\",\n      container!=\"POD\", container!=\"\",\n      namespace =~ \"rhsm-stage|rhsm-prod\"\n    }[14d:]\n  ) / 1024 / 1024\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max Memory",
     "type": "table",
     "gridPos": { "h": 9, "w": 10, "x": 11, "y": 30 },
     "targets": [
      {
       "expr": "max by (container,namespace) (\nmax_over_time(\ncontainer_memory_working_set_bytes{\ncluster = \"\",\ncontainer!=\"POD\", container!=\"\",\nnamespace =~ \"rhsm-stage|rhsm-prod\"\n}[14d:]\n) / 1024 / 1024\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}