{
 "title": "Subscription Watch - PAYG metrics",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "product",
    "label": "Product",
    "query": {
     "query": "label_values(swatch_billable_usage_total,product)"
    }
   },
   {
    "name": "metric_id",
    "label": "Metric",
    "query": {
     "query": "label_values(swatch_billable_usage_total,metric_id)"
    }
   },
   {
    "name": "billing_provider",
    "label": "Billing Provider",
    "query": {
     "query": "label_values(swatch_billable_usage_total,billing_provider)"
    }
   },
   { "name": "interval", "query": "'$__range',1h,2h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "Metered end-to-end stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stats for \"$product\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "repeat": "product",
   "targets": [
    {
     "expr": "sum(increase(swatch_billable_usage_total{metric_id=\"$metric_id\", product=\"$product\", billing_provider=\"$billing_provider\"}[$interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(swatch_tally_tallied_usage_total{metric_id=\"$metric_id\", product=\"$product\", billing_provider=\"$billing_provider\"}[$interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(swatch_contract_usage_total{metric_id=\"$metric_id\", product=\"$product\", billing_provider=\"$billing_provider\"}[$interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(swatch_billable_usage_total{metric_id=\"$metric_id\", product=\"$product\", billing_provider=\"$billing_provider\"}[$interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(swatch_producer_metered_total{metric_id=\"$metric_id\", product=\"$product\", billing_provider=\"$billing_provider\", status=\"failed\"}[$interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(swatch_producer_metered_total{metric_id=\"$metric_id\", product=\"$product\", billing_provider=\"$billing_provider\", status=\"succeeded\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stats by metrics for $product",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "repeat": "product",
   "collapsed": true,
   "panels": [
    {
     "title": "Metered",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(increase(swatch_billable_usage_total{product=\"$product\", billing_provider=\"$billing_provider\"}[$interval])) by (metric_id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tallied",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum(increase(swatch_tally_tallied_usage_total{product=\"$product\", billing_provider=\"$billing_provider\"}[$interval])) by (metric_id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Covered by contract",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(swatch_contract_usage_total{product=\"$product\", billing_provider=\"$billing_provider\"}[$interval])) by (metric_id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Billing Pending",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(swatch_billable_usage_total{product=\"$product\", billing_provider=\"$billing_provider\"}[$interval])) by (metric_id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Remitted Success",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(increase(swatch_producer_metered_total{product=\"$product\", billing_provider=\"$billing_provider\", status=\"succeeded\"}[$interval])) by (metric_id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Remitted Failed with Subscription Not Found",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum(increase(swatch_producer_metered_total{product=\"$product\", billing_provider=\"$billing_provider\", status!=\"succeeded\",error_code=\"subscription_not_found\"}[$interval])) by (metric_id, error_code)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Remitted Failed with Unknown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum(increase(swatch_producer_metered_total{product=\"$product\", billing_provider=\"$billing_provider\", status!=\"succeeded\",error_code!=\"subscription_not_found\"}[$interval])) by (metric_id, error_code)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}