openapi: "3.0.2"
info:
  title: "rhsm-subscriptions-api"
  description: "REST interface for the rhsm-subscriptions service."
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/rhsm-subscriptions/v1
  - url: https://ci.cloud.redhat.com/api/rhsm-subscriptions/v1
  - url: https://qa.cloud.redhat.com/api/rhsm-subscriptions/v1
  - url: https://stage.cloud.redhat.com/api/rhsm-subscriptions/v1
  - url: https://cloud.redhat.com/api/rhsm-subscriptions/v1

paths:
  /version:
    description: "Provides version and build information about the deployed application."
    get:
      summary: "Request version and build information about the deployed application."
      operationId: getVersion
      tags:
        - version
      responses:
        '200':
          description: 'The request for version information was successful.'
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/VersionInfo"
        '500':
          $ref: '#/components/responses/InternalServerError'
  /tally/products/{product_id}:
    description: "Operations for a tally report of a specific account and product."
    parameters:
      - name: product_id
        in: path
        required: true
        schema:
          type: string
        description: "The ID for the product we wish to query"
      - name: offset
        in: query
        schema:
          type: integer
        description: "The number of items to skip before starting to collect the result set"
      - name: limit
        in: query
        schema:
          type: integer
        description: "The numbers of items to return"
    get:
      summary: "Fetch a tally report for an account and product. If page header parameters are omitted,
                then any gaps in the resulting report snapshots are filled with a default fake snapshot."
      operationId: getTallyReport
      parameters:
        - name: granularity
          in: query
          required: true
          schema:
            type: string
          description: "The level of granularity to return."
        - name: beginning
          in: query
          required: true
          schema:
            type: string
            format: date-time
          description: "Defines the start of the report period. Dates should be provided in ISO 8601
            format but the only accepted offset is UTC. E.g. 2017-07-21T17:32:28Z"
        - name: ending
          in: query
          required: true
          schema:
            type: string
            format: date-time
          description: "Defines the end of the report period.  Defaults to the current time. Dates should
            be provided in UTC."
      responses:
        '200':
          description: 'The request for a tally report was successful.'
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/TallyReport"
              example:
                data:
                  - date: '2017-08-04T17:32:05Z'
                    instance_count: 5
                    cores: 10
                    sockets: 5
                  - date: '2017-08-05T17:31:04Z'
                    instance_count: 7
                    cores: 14
                    sockets: 7
                  - date: '2017-08-06T17:32:03Z'
                    instance_count: 20
                    cores: 20
                    sockets: 10
                  - date: '2017-08-07T17:34:02Z'
                    instance_count: 7
                    cores: 14
                    sockets: 7
                  - date: '2017-08-08T17:32:01Z'
                    instance_count: 5
                    cores: 10
                    sockets: 5
                links:
                  first: '/api/rhsm-subscriptions/v1/tally/products/RHEL?granularity=DAILY&beginning=2017-08-01T17%3A32%3A28Z&ending=2017-08-31T17%3A32%3A28Z&offset=0&limit=5'
                  last: '/api/rhsm-subscriptions/v1/tally/products/RHEL?granularity=DAILY&beginning=2017-08-01T17%3A32%3A28Z&ending=2017-08-31T17%3A32%3A28Z&offset=5&limit=5'
                  previous: null
                  next: '/api/rhsm-subscriptions/v1/tally/products/RHEL?granularity=DAILY&beginning=2017-08-01T17%3A32%3A28Z&ending=2017-08-31T17%3A32%3A28Z&offset=5&limit=5'
                meta:
                  count: 10
                  product: RHEL
                  granularity: DAILY
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/ResourceNotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
      tags:
        - tally
  /capacity/products/{product_id}:
    description: 'Operations for capacity report for a given account and product'
    parameters:
      - name: product_id
        in: path
        required: true
        schema:
          type: string
        description: "The ID for the product we wish to query"
      - name: offset
        in: query
        schema:
          type: integer
        description: "The number of items to skip before starting to collect the result set"
      - name: limit
        in: query
        schema:
          type: integer
        description: "The numbers of items to return"
    get:
      summary: "Fetch a capacity report for an account and product."
      operationId: getCapacityReport
      parameters:
        - name: granularity
          in: query
          required: true
          schema:
            type: string
          description: "The level of granularity to return."
        - name: beginning
          in: query
          required: true
          schema:
            type: string
            format: date-time
          description: "Defines the start of the report period. Dates should be provided in ISO 8601
            format but the only accepted offset is UTC. E.g. 2017-07-21T17:32:28Z"
        - name: ending
          in: query
          required: true
          schema:
            type: string
            format: date-time
          description: "Defines the end of the report period.  Defaults to the current time. Dates should
            be provided in UTC."
      responses:
        '200':
          description: 'The request for a capacity report was successful.'
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/CapacityReport"
              example:
                data:
                  - date: '2017-08-04T17:32:05Z'
                    sockets: 0
                    has_infinite_quantity: false
                  - date: '2017-08-05T17:31:04Z'
                    sockets: 0
                    has_infinite_quantity: false
                  - date: '2017-08-06T17:32:03Z'
                    sockets: 10
                    has_infinite_quantity: false
                  - date: '2017-08-07T17:34:02Z'
                    sockets: null
                    has_infinite_quantity: true
                  - date: '2017-08-08T17:32:01Z'
                    sockets: 10
                    has_infinite_quantity: true
                links:
                  first: '/api/rhsm-subscriptions/v1/capacity/RHEL?granularity=DAILY&beginning=2017-08-01T17%3A32%3A28Z&ending=2017-08-31T17%3A32%3A28Z&offset=0&limit=5'
                  last: '/api/rhsm-subscriptions/v1/capacity/RHEL?granularity=DAILY&beginning=2017-08-01T17%3A32%3A28Z&ending=2017-08-31T17%3A32%3A28Z&offset=5&limit=5'
                  previous: null
                  next: '/api/rhsm-subscriptions/v1/capacity/RHEL?granularity=DAILY&beginning=2017-08-01T17%3A32%3A28Z&ending=2017-08-31T17%3A32%3A28Z&offset=5&limit=5'
                meta:
                  count: 10
                  product: RHEL
                  granularity: DAILY
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/ResourceNotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
      tags:
        - capacity
  /openapi.json:
    get:
      description: "Get the OpenAPI spec in JSON format."
      operationId: getOpenApiJson
      tags:
        - root
      responses:
        '200':
          description: "The request to get the OpenAPI JSON was successful."
          content:
            application/json:
              schema:
                type: string
  /openapi.yaml:
    get:
      description: "Get the OpenAPI spec in YAML format."
      operationId: getOpenApiYaml
      tags:
        - root
      responses:
        '200':
          description: "The request to get the OpenAPI YAML was successful."
          content:
            application/x-yaml:
              schema:
                type: string

components:
  securitySchemes:
    3ScaleIdentity:
      type: apiKey
      in: header
      name: x-rh-identity
      description: >-
        Base64-encoded JSON identity header provided by 3Scale. Contains an
        account number of the user issuing the request. Format of the JSON:
        {"identity": {"account_number": "12345678"}}
  responses:
    InternalServerError:
      description: "An internal server error has occurred and is not recoverable."
      content:
        application/vnd.api+json:
          schema:
            $ref: "#/components/schemas/Errors"
    BadRequest:
      description: "The server could could not process the current request."
      content:
        application/vnd.api+json:
          schema:
            $ref: "#/components/schemas/Errors"
    Forbidden:
      description: "The request was valid, but the request was refused by the server."
      content:
        application/vnd.api+json:
          schema:
            $ref: "#/components/schemas/Errors"
    ResourceNotFound:
      description: "The requested resource was not found."
      content:
        application/vnd.api+json:
          schema:
            $ref: "#/components/schemas/Errors"
    ServiceUnavailable:
      description: "The server is currently unavailable."
      content:
        application/vnd.api+json:
          schema:
            $ref: "#/components/schemas/Errors"
  schemas:
    VersionInfo:
      properties:
        build:
          type: object
          properties:
            version:
              type: string
            gitDescription:
              type: string
            artifact:
              type: string
            name:
              type: string
            group:
              type: string
            gitHash:
              type: string
    # If we need additional responses, look at
    # https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/ to reduce
    # redundancy
    TallyReport:
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/TallySnapshot"
        links:
          type: object
          properties:
            first:
              type: string
            last:
              type: string
            previous:
              type: string
            next:
              type: string
          required:
            - first
            - previous
            - last
            - next
        meta:
          type: object
          properties:
            count:
              type: integer
            product:
              type: string
            granularity:
              description: "Describes the significance of each date in the TallySnapshot list. For example if the
                granularity is set to 'weekly', the dates in the TallySnapshot list will represent the start of a
                seven day period."
              type: string
          required:
            - count
            - product
            - granularity
    TallySnapshot:
      # Container for fields we capture from the IT endpoint for upload to inventory service.  The element
      # being reported should be the only non-required element.  E.g. snapshots containing memory will have
      # date, instance count, and memory elements while snapshots containing cores will contain date,
      # instance count, and cores.
      required:
        - date
        - instance_count
      properties:
        date:
          type: string
          format: date-time
          description: "The start date for this snapshot entry. Dates are returned in UTC. Clients must
            consult the 'granularity' field in the TallyReport to determine the length of time each
            TallySnapshot covers."
        instance_count:
          type: integer
          format: int32
          minimum: 0
        cores:
          type: integer
          format: int32
          minimum: 0
        sockets:
          type: integer
          format: int32
          minimum: 0
        has_data:
          type: boolean
    CapacityReport:
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/CapacitySnapshot"
        links:
          type: object
          properties:
            first:
              type: string
            last:
              type: string
            previous:
              type: string
            next:
              type: string
          required:
            - first
            - previous
            - last
            - next
        meta:
          type: object
          properties:
            count:
              type: integer
            product:
              type: string
            granularity:
              description: "Describes the significance of each date in the CapacitySnapshot list. For example if the
                granularity is set to 'weekly', the dates in the CapacitySnapshot list will represent the start of a
                seven day period."
              type: string
          required:
            - count
            - product
            - granularity
    CapacitySnapshot:
      required:
        - date
        - has_infinite_quantity
      properties:
        date:
          type: string
          format: date-time
          description: "The start date for this snapshot entry. Dates are returned in UTC. Clients must
            consult the 'granularity' field in the CapacityReport to determine the length of time each
            CapacitySnapshot covers."
        sockets:
          type: integer
          format: int32
          minimum: 0
        has_infinite_quantity:
          description: "Indicates whether this snapshot has an infinite quantity subscription included.
            If there is an infinite quantity subscription involved, there is no meaningful number for
            capacity."
          type: boolean
    Errors:
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: "#/components/schemas/Error"
    Error:
      required:
        - status
        - code
        - title
      properties:
        status:
          type: string
        code:
          type: string
        title:
          type: string
        detail:
          type: string

security:
  - 3ScaleIdentity: []
