# This is a file maintained by the rhsm-subscription project that describes
# a portion of the Marketplace API.
openapi: 3.0.2
info:
  title: rh-marketplace-api
  description: Third-party specification for Red Hat Marketplace API, see https://marketplace.redhat.com/en-us/documentation/api-reference
  version: 1.0.0

paths:
  /api-security/om-auth/cloud/token:
    post:
      operationId: getAccessToken
      tags:
        - rh_marketplace
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                apikey:
                  type: string
      responses:
        '200':
          description: The operation completed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
  /metering/api/v1/metrics:
    post:
      operationId: submitUsageEvents
      tags:
        - rh_marketplace
      security:
        - accessToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsageRequest"
      responses:
        '200':
          description: The operation completed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
  /metering/api/v1/metrics/{batchId}:
    parameters:
      - name: batchId
        required: true
        in: path
        schema:
          type: string
    get:
      operationId: getUsageBatchStatus
      tags:
        - rh_marketplace
      security:
        - accessToken: []
      responses:
        '200':
          description: Batch status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"


components:
  schemas:
    AuthGrantType:
      type: string
      enum: [ "urn:ibm:params:oauth:grant-type:apikey" ]
    AuthResponse:
      required:
        - access_token
        - expiration
      properties:
        access_token:
          type: string
        expiration:
          type: integer
          format: int64
    UsageRequest:
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/UsageEvent"
    UsageEvent:
      required:
        - start
        - end
        - subscriptionId
        - eventId
        - additionalAttributes
        - measuredUsage
      properties:
        start:
          description: Start time of the usage in millseconds since Unix epoch.
          type: integer
          format: int64
        end:
          description: End time of the usage in millseconds since Unix epoch.
          type: integer
          format: int64
        subscriptionId:
          type: string
        eventId:
          description: Event ID for Marketplace API.
          type: string
        additionalAttributes:
          type: object
        measuredUsage:
          type: array
          items:
            $ref: "#/components/schemas/UsageMeasurement"
    UsageMeasurement:
      required:
        - metricId
        - value
      properties:
        chargeId:  # NOTE: metricId is used in the request, but becomes chargeId in the response
          type: string
        metricId:
          type: string
        value:
          type: number
          format: double
    StatusResponse:
      properties:
        status:
          type: string
        message:
          type: string
        data:
          type: array
          items:
            $ref: "#/components/schemas/BatchStatus"
    BatchStatus:
      properties:
        status:
          type: string
        message:
          type: string
        batchId:
          type: string
        payload:
          $ref: "#/components/schemas/UsageEvent"

  securitySchemes:
    accessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
